# Generated by Django 5.1.2 on 2026-01-18 15:28

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('STUDENT', 'STUDENT'), ('INSTRUCTOR', 'INSTRUCTOR'), ('TPO', 'TPO'), ('INTERVIEWER', 'INTERVIEWER'), ('ADMIN', 'ADMIN')], max_length=25)),
                ('phone_no', models.PositiveBigIntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_email', models.EmailField(max_length=254)),
                ('ins_name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('instructor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to='crt_app.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_name', models.CharField(max_length=250)),
                ('int_email', models.EmailField(max_length=200)),
                ('sub', models.CharField(choices=[('TECH', 'TECH'), ('HR', 'HR'), ('GD_EXTEMPORE', 'GD_EXTEMPORE')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=250)),
                ('stu_email', models.EmailField(max_length=200)),
                ('rtu_roll_no', models.CharField(max_length=30, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('AIDS', 'AIDS'), ('MECH', 'MECH'), ('ELEC', 'ELEC'), ('CIVIL', 'CIVIL'), ('ECE', 'ECE'), ('IT', 'IT'), ('CSAI', 'CSAI')], max_length=25)),
                ('attendance', models.IntegerField(default=0)),
                ('tpo_email', models.EmailField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('TECH', 'TECH'), ('HR', 'HR'), ('GD_EXTEMPORE', 'GD_EXTEMPORE')], max_length=70)),
                ('date', models.DateField(null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('interviewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_profile', to='crt_app.interviewerprofile')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_performance', to='crt_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('class_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_object', to='crt_app.classes')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='crt_app.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TPOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpo_name', models.CharField(max_length=250)),
                ('tpo_email', models.EmailField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tpo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpo_profile', to='crt_app.tpoprofile'),
        ),
    ]
