# Generated by Django 6.0.1 on 2026-01-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('instructor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to='crt_app.instructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='crt_app.studentprofile')),
                ('class_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_object', to='crt_app.classes')),
            ],
        ),
    ]
