# Generated by Django 6.0.1 on 2026-01-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0002_alter_attendance_class_obj_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to='crt_app.instructorprofile'),
        ),
    ]
