# Generated by Django 5.1.2 on 2026-01-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0003_alter_classes_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_profile', to='crt_app.interviewerprofile'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performance', to='crt_app.studentprofile'),
        ),
    ]
