# Generated by Django 6.0.1 on 2026-01-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crt_app', '0004_alter_performance_interviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='tpo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tpo_profile', to='crt_app.tpoprofile'),
        ),
    ]
